services:
  - type: static_site
    name: skill-swap-frontend
    rootDir: .
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_APPWRITE_ENDPOINT
        value: https://sgp.cloud.appwrite.io/v1
      - key: VITE_APPWRITE_PROJECT_ID
        value: 697777ab003b4896ab21
